changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking
    - title: New Features ➕
      labels:
        - enhancement
    - title: Bug-fixes 🐛
      labels:
        - bugfix
    - title: Other Changes➡️
      labels:
        - "*"
