# produce a test coverage artifact
name: coverage

on:
  workflow_call:
  
jobs:
  setup-racket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Racket dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/racket
            ~/.local/share/racket
          key: ${{ runner.os }}-racket-8.5

      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.8.1
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: '8.5'

      - name: Install Dependencies
        run: raco pkg install --auto --skip-installed cover
        
      - run: raco cover -Q src test
      
      - name: Archive code coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage
