
name: CI Tests

on:
  push:
    paths-ignore:
      - '*README.md'
  pull_request:
    paths-ignore:
      - '*README.md'
      
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.8.1
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: '8.5'
          
      - name: Run Tests
        run: raco test -e --timeout 120 -q --table --jobs 6 src test
        
