
name: CI Tests

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.6.1
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: '8.2'
          
      - name: Install Dependencies
        run: raco pkg install --auto component cover
        
      - name: Run Tests
        run: raco test -e --timeout 120 --table --jobs 10 src
        
      - run: raco cover src
      - name: Archive code coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage
        
